# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc94543adc83f2e8a9288ab919b911f4f63b1f6a0df5f1e39056c489e4a79ce0e989abfd36b60b287f01fac6e8108e4725bbc272e800ba92f689db832154d8e7

test:
  secret_key_base: 56684ced7089a380e32c5a52438a41dd6545fa7d47bd082c489e6fb7f5bdf7dab9505103e8e8e85bb7244685f70f77261ceee10cadde39ec47767bc5edf0c862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
